import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AllProductsProvider } from "@/allContext/allproducts";
import { CartProvider } from "@/allContext/cart";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@400..800&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased baloo-2-all h-full`}
      >
        <AllProductsProvider>
          <CartProvider>
            {children}
          </CartProvider>
        </AllProductsProvider>
      </body>
    </html>
  );
}
